### PR TITLE
Test with the right Django version ; Add and fix 1.9 tests

### PR DESCRIPTION
**Pull request by roidelapluie**
Prior to this commit, the tests were running with Django 1.8 because it
is in requirements.txt, which was installed after the specific version
of Django.

This commit inverts that order, allowing the defined version of Django
to be used for testing.

### CODE REVIEW

**Comment by roidelapluie** [comment]
@jrief is there somthing blocking this PR?

**Comment by nanuxbe** [comment]
@roidelapluie could you just update Django versions to 1.8.8 and 1.9.1?
Except for that, looks good to me

**Comment by roidelapluie** [comment]
Done

**Comment by nanuxbe** [comment]
It is failing for Python 3.3 and Django 1.9.1. Since Django 1.9 only supports python 3.4 & 3.5, I guess you can simply remove testing for python 3.3 under Django 1.9

**Comment by roidelapluie** [comment]
Sorry, it was there for 1.9, not 1.9.1. Amended and fixed.

**Comment by nanuxbe** [comment]
thanks @roidelapluie :-)

**Pull request merged**
