### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by nanuxbe**
Inspired by @0nkery 's django-wenbsocket-redis3

### CODE REVIEW

**Comment by jrief** [comment]
Thank you very much for this PR.
I'm just wondering why Travis-CI didn't trigger a unit test run.
Did all tests pass when you ran this version locally?

**Comment by nanuxbe** [comment]
Noyt sure why it didn't trigger either.
Locally I had a failing test (before and after the PR) `FAIL: test_forbidden_channel (chatserver.tests.test_chatclient.WebsocketTests)` but on travis (on my fork) all tests pass: https://travis-ci.org/nanuxbe/django-websocket-redis/builds/84104155

**Comment by jrief** [comment]
all green :)
Thanks

**Comment by nanuxbe** [comment]
You're welcome ;-)

**Pull request merged**
