### PR TITLE
Selenium testing

### PR DESCRIPTION
**Pull request by roidelapluie**
This Pull Request adds basic Selenium testing.

It uses two browsers simulataneously: Chrome and Firefox.

### CODE REVIEW

**Comment by roidelapluie** [comment]
There is a big problem with the static files. I need to use `collectstatic` and `DjangoWhiteNoise`. I did not find any other way to do this.

**Comment by roidelapluie** [comment]
I have enabled travis on https://github.com/roidelapluie/django-websocket-redis

If you think you can remove that staticfiles hack, you can make a pull request against the selenium branch.

**Comment by nanuxbe** [comment]
@roidelapluie the test looks good but it is not failing for me on the currently available version from pypi.

**Comment by roidelapluie** [comment]
Yes, because this test is simple. When we will add other tests and force the browser to close that will trigger them.

**Comment by roidelapluie** [comment]
@nanuxbe @jrief I have updated that PR and removed the dependency to whitenose.

**Comment by roidelapluie** [comment]
No time for this :(

**Pull request closed without merging**
