### PR TITLE
-add Sec-WebSocket-Protocol to header only if it exists in request header

### PR DESCRIPTION
**Pull request by eddiep1101**

### CODE REVIEW

**Comment by ErwinJunge** [comment]
The code as it is now is broken (you need to append a tuple instead of 2 values). 

Other than that, this looks fine to me. According to [the RFC](https://tools.ietf.org/html/rfc6455) we should return null or nothing in the case the client doesn't specify a subprotocol:
```
/subprotocol/
          Either a single value representing the subprotocol the server
          is ready to use or null.  The value chosen MUST be derived
          from the client's handshake, specifically by selecting one of
          the values from the |Sec-WebSocket-Protocol| field that the
          server is willing to use for this connection (if any).  If the
          client's handshake did not contain such a header field or if
          the server does not agree to any of the client's requested
          subprotocols, the only acceptable value is null.  The absence
          of such a field is equivalent to the null value (meaning that
          if the server does not wish to agree to one of the suggested
          subprotocols, it MUST NOT send back a |Sec-WebSocket-Protocol|
          header field in its response).  The empty string is not the
          same as the null value for these purposes and is not a legal
          value for this field.  The ABNF for the value of this header
          field is (token), where the definitions of constructs and
          rules are as given in [RFC2616].
```
Just one thing, could you add a test for this case to https://github.com/jrief/django-websocket-redis/blob/master/examples/chatserver/tests/test_chatclient.py ?

**Comment by roidelapluie** [comment]
I think this is now fixed in master and can be closed

**Comment by ErwinJunge** [comment]
Indeed. I added these commits to PR #154

**Comment by roidelapluie** [comment]
@jrief please close this one :-)

**Pull request closed without merging**
