### PR TITLE
Add Django 2.1.5 and latest support.

### PR DESCRIPTION
**Pull request by DaniilSezonov**
Close issue #286.

### CODE REVIEW

**Comment by gtnx** [comment]
Looks good.
@jrief I see that last merged PR was almost one year ago. Have you considered integrating other maintainers?

**Comment by jrief** [comment]
> Have you considered integrating other maintainers?

Yes, but noone asked until now. Would you like to become one?

**Comment by gtnx** [comment]
Yes.
I use this package in production in my company for almost 4 years now. I'm not super familiar with this package codebase but i can totally support you on those kind of tickets which are important for the community.

**Comment by gtnx** [comment]
@DaniilSezonov Could you add the 2.1.5 to the ci matrix. IT's in `travis.yml` in the `env` section?
Thanks

**Comment by jrief** [comment]
btw., what's your username on PyPI?

**Comment by DaniilSezonov** [comment]
Something was wrong, sorry, I have no experience with CI/CD configuration.

**Comment by DaniilSezonov** [comment]
Trying again

**Comment by gtnx** [comment]
@jrief this is [guillaume.thomas](https://pypi.org/user/guillaume.thomas/)

**Comment by gtnx** [comment]
As i said it looks good. I tested it using a personal project and not the example project which still needs to be compatible with latest django versions (See #246).

**Comment by gtnx** [comment]
@jrief Could you add me as well on pypi? Thanks

**Pull request merged**
